steps:
  # 1. Build da imagem Docker com argumentos do ambiente
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest'
      - '--build-arg'
      - 'VITE_PARSE_APP_ID=$_VITE_PARSE_APP_ID'
      - '--build-arg'
      - 'VITE_PARSE_JS_KEY=$_VITE_PARSE_JS_KEY'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '.'

  # 2. Push da imagem Docker para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest']

  # 3. Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
