steps:
  # 1. Build da imagem Docker com argumentos do ambiente
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/oss-manager-image'
      - '--build-arg'
      - 'VITE_PARSE_APP_ID=$_VITE_PARSE_APP_ID'
      - '--build-arg'
      - 'VITE_PARSE_JS_KEY=$_VITE_PARSE_JS_KEY'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '.'

  # 2. Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME' # O nome do serviço configurado nas variáveis do seu gatilho
      - '--image'
      - 'gcr.io/$PROJECT_ID/oss-manager-image'
      - '--region'
      - '$_DEPLOY_REGION' # A região configurada nas variáveis do seu gatilho
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/oss-manager-image'

options:
  logging: CLOUD_LOGGING_ONLY
